const CONFIG = {
  
  letter: {
    paragraph1: `Sparsh Roy, Zuzu Ghauri :)
December 11, 2025
To: Ms. Zara Uddin`,
    paragraph2: `Dear Zara Uddin,

After hearing the solemn news, we wanted to express our genuine gratitude and appreciation to you, hopefully lifting your spirits. It’s like really evident how much effort and heart you put into the things you do, and we really hope this letter brings you some encouragement and reminds you of how awesome you are (we need to follow in the footsteps of our inspiration, yk, because whenever we are sad you always make us happier)`,
    paragraph3: `Ok for my segment (Sparsh) like dude Im SUPER grateful that I met you in RUMUN 2024 and I hopefully? Told you this during Thanksgiving and even though I think that im the networking goat out of all the people I’ve met like genuinely you are one of the funniest I know, EXCEPT when at the philmun social you told the guys from my school that I was a discord mod (I got slimed out </3  AND WAS ALSO FAKE IM NOT A DISCORD MOD !!!! )`,
    paragraph4: `Also like you’re famous in Hopewell Valley MUN because of your aura like I used YOU as a recruiting example (idk if this is ethical but this is high school mun recruiting not the corporate world not like u can sue me) but I was telling everyone how in model united nations you get to meet so many great people and I used “Zara Uddin” as an example because your lowk one of the GREATEST people i have ever met And but like even with all of this you’re still like a frigging GENIUS you know like guys this is ms NHSMUN BEST DELEGATE btw not a small task by anymeans and lowk you have the most aura out of everyone I know (EVEN MORE THAN ME)`,
    paragraph5: `Also, you’re also otapped into great anime, and your recommendations are super heat like Loving Yamada to Lv 999 and Fruits Basket were honestly TOP TIER.`,
    paragraph6: `And also I GENIUENLY want to apologize for all the times I was mean like when I said like you look like shrek I also did that alot and it was very mean and immature and like when I’ve just been a hater in general like I really regret it and I want you to know like on the last day of Rumun 2025 I was like super sad because like it could’ve been the last time I ever see you and I was like idk just upset and I hope that shows you just how cool you are idk im just yapping I guess maybe zuzu will fix my writing idk you just like matter alot to me yk idk`,
    paragraph7: `And also genuinely like I hope you know that like when all those guys were dming Sidnie telling her I like her, and u stood up for me like you don't know how much i genieunly appreciated you then. Like dude I was actually freaking out when like adam and those other guys were dming her and I was so mad because they thought it was funny but then you lowk like a knight in shining armor like yelled at them and got them to stop and even helped me through those tough times when I was like depressed that she didn’t want to talk to me and like you SERIOUSLY were like SOOO awesome like you dont understand like even at school with people Im with everyday they still like to this day bully me about it cuz like almost everyone found out but you being such a kind person that you are even though we haven’t even know each other for that long although it SOOO feels like i’ve known you forever were like one of the only peoples who were like nice to me and got me through that whole thinIg`,
    paragraph8: `And also like ur such an inspiration yk like when I grow up the typa person i wanna be is lowk like you`,
    paragraph9: `and like I just want you to know that EVERYTHING I said here is genuinely from the bottom of my heart and youre honestly so great and one day when ur super rich and famous 20 years down the line princetons gonna be like “O zara can u pls come give a speech to our graduating class and you’ll be like uhm no and reject them!!!!” Also like we’re basically twins, we both know the same niche bengali dialect Sylheti. Anyway ts is your Bengali #fishlovergang homie signing out!`,
    paragraph10: `Nowww it is zuzu’s turnnn!!! First I want to say that you are absolutely one of my favorite people ever even though I’ve only known you personally for a few  months. But to be honest one of the main reasons why I joined mun was because Fola and friends kept glazing you and you seemed so super duper cool like an untouchable goddess or smth and I like really looked up to you before you even knew my name (probably). Then I FINALLY got the courage to try out for model un and I after I got in you were like absolutely the nicest person ever like I was so scared because not many people knew me but you still did like the smallest things like reply to me on the mun group chat and it actually made me feel so happy and included so thank you so so much for thattt.`,
    paragraph11: `and OMG when that budget cut happened at the beginning of the year I felt so bad how everyone was bombarding you like it was your fault BUT you actually handled that so welllll. you are such a natural born leader its actually insane i aspire to be like you so so so much. i love the way you are so social and friendly to everyone while being so super duper smart at the same time.`,
    paragraph12: `I’ve also ONLY ever heard good things about you like I will actually bet 100000 dollars that you do not have a single hater on this planet bc who could EVER hate somebody like you <3 whenever i hear anybody talk about you it’s always about how nice you are and how special and happy you make them feel its like the universal zara effect at this point. i’ve heard from sparsh and fola and yug and sujaan and zahra about how extremely fun you are to talk to and how amazing you are.`,
    paragraph13: `i also loveee your teaching skills like everyone else are such haters saying that you’re a bad teacher and didn’t prepare them because i kid you not the ONLY reason i awarded at both fhsmun and rumun was because of your guidance and feedback and the time you put in to help everyone. especially for rumun i know how busy you were preparing for your own committee yet you still read our position papers and speeches and gave us advice and tips and everything i appreciate that so so much since nobody else was willing to step up and help. best mun president in all of history!!`,
    paragraph14: `not to mention how you call me a mun prodigy but you literally got NHSMUN BEST DEL!!! like hello the skill that takes is extremely insane you need speaking and research and leadership and amazingness (and you have them all in surplus istg) so please dont ever discredit yourself based on some stinky dinky college or chair since they fail to see the goat that stands right before them.`,
    paragraph15: `just ALWAYS remember that it does not matter how some stingy stinky bum college sees you since these hundreds of other people love you so so much <33`,
    paragraph16: `With Much love and support,
Zuzu :) and Sparsh :P`
  },
  
  
  seedText: 'from\nSparsh & Zuzu!'
};